import 'package:test/test.dart';
import 'package:xcode_parser/xcode_parser.dart';

void main() {
  group('CommentPbx Tests', () {
    late CommentPbx commentPbx;

    setUp(() {
      commentPbx = CommentPbx('!!\$*UTF8*\$!');
    });

    test('String representation with default indentation', () {
      final str = commentPbx.toString();
      expect(str, '// !!\$*UTF8*\$!\n');
    });

    test('String representation with indentation', () {
      final str = commentPbx.toString(indentLevel: 2, removeN: false);
      expect(str, '\t\t// !!\$*UTF8*\$!\n');
    });

    test('CopyWith method with new comment', () {
      final copied = commentPbx.copyWith(comment: 'Generated by Xcode');
      expect(copied.comment, 'Generated by Xcode');
    });

    test('CopyWith method without changes', () {
      final copied = commentPbx.copyWith();
      expect(copied.comment, '!!\$*UTF8*\$!');
    });
  });
}
