import 'dart:io';

import 'package:test/test.dart';
import 'package:xcode_parser/xcode_parser.dart';

void main() {
  group('Pbxproj Tests', () {
    late Pbxproj pbxproj;
    late MapPbx component;
    late String tempFilePath;

    setUp(() async {
      final tempDir = Directory.systemTemp.createTempSync();
      tempFilePath = '${tempDir.path}/test_project.pbxproj';
      pbxproj = Pbxproj(path: tempFilePath);
      component = MapPbx(
        uuid: 'AA11BB22CC33DD44EE55FF66',
        children: [
          MapEntryPbx('isa', VarPbx('PBXBuildFile')),
        ],
        comment: 'main.swift in Sources',
      );
    });

    tearDown(() async {
      final file = File(tempFilePath);
      if (await file.exists()) {
        await file.parent.delete(recursive: true);
      }
    });

    test('Open Pbxproj file', () async {
      final file = File(tempFilePath);
      await file.create(recursive: true);
      await file.writeAsString(
          '// !\$*UTF8*\$!\n{\n\t// generated by xcode_parser\n}\n');
      final openedProject = await Pbxproj.open(tempFilePath);
      expect(openedProject.path, tempFilePath);
      expect(openedProject.childrenList.first, isA<CommentPbx>());
    });

    test('Open Pbxproj file from string', () {
      final openedProject = Pbxproj.parse(
          '// !\$*UTF8*\$!\n{\n\t// generated by xcode_parser\n}\n',
          path: tempFilePath);
      expect(openedProject.path, tempFilePath);
      expect(openedProject.childrenList.first, isA<CommentPbx>());
    });

    test('Save Pbxproj file', () async {
      await pbxproj.save();
      final file = File(tempFilePath);
      expect(await file.exists(), isTrue);
      final content = await file.readAsString();
      expect(content, '// !\$*UTF8*\$!\n{\n}\n');
    });

    test('Add NamedComponent', () {
      pbxproj.add(component);
      expect(pbxproj.childrenList, contains(component));
      expect(pbxproj.childrenMap[component.uuid], component);
    });

    test('Remove NamedComponent by UUID', () {
      pbxproj.add(component);
      pbxproj.remove(component.uuid);
      expect(pbxproj.childrenList, isNot(contains(component)));
      expect(pbxproj.childrenMap[component.uuid], isNull);
    });

    test('Replace or Add NamedComponent', () {
      pbxproj.add(component);
      final newComponent = MapPbx(
        uuid: 'AA11BB22CC33DD44EE55FF66',
        children: [
          MapEntryPbx('isa', VarPbx('PBXFileReference')),
        ],
        comment: 'AppDelegate.swift',
      );
      pbxproj.replaceOrAdd(newComponent);
      expect(pbxproj.childrenList, contains(newComponent));
      expect(pbxproj[component.uuid], newComponent);
    });

    test('Find NamedComponent by UUID', () {
      pbxproj.add(component);
      final found = pbxproj.find<MapPbx>('AA11BB22CC33DD44EE55FF66');
      expect(found, component);
    });

    test('Find NamedComponent by Comment', () {
      pbxproj.add(component);
      final found = pbxproj.findComment<MapPbx>('main.swift in Sources');
      expect(found, component);
    });

    test('Generate unique UUID', () {
      final uuid1 = pbxproj.generateUuid();
      final uuid2 = pbxproj.generateUuid();
      expect(uuid1, isNot(uuid2));
      expect(uuid1.length, 24);
      expect(RegExp(r'^[0-9A-F]{24}$').hasMatch(uuid1), isTrue);
    });

    test('String representation', () {
      final str = pbxproj.toString();
      expect(str, '// !\$*UTF8*\$!\n{\n}\n');
    });

    test('CopyWith method', () {
      pbxproj.add(component);
      final newComponent = MapPbx(
        uuid: 'BB22CC33DD44EE55FF660011',
        children: [
          MapEntryPbx('isa', VarPbx('PBXGroup')),
        ],
        comment: 'Products',
      );
      final newPath = '${Directory.systemTemp.path}/new_project.pbxproj';
      final copiedPbxproj = pbxproj.copyWith(
        children: [newComponent],
        path: newPath,
      );

      expect(copiedPbxproj.path, newPath);
      expect(copiedPbxproj.childrenList, contains(newComponent));
      expect(copiedPbxproj.childrenMap[newComponent.uuid], newComponent);
      expect(copiedPbxproj.childrenList, isNot(contains(component)));
      expect(copiedPbxproj.childrenMap[component.uuid], isNull);
    });
  });
}
