name: xcode_parser
description: Xcode Parser is a package for working with Xcode project files (.pbxproj). This package allows you to read, modify, and save changes in .pbxproj files, which is especially useful for automating iOS development tasks.
version: 1.0.2
repository: https://github.com/EclipseAndrey/xcode_parser
homepage: https://github.com/EclipseAndrey/xcode_parser

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
